name: Backend linter (pylint)
on: [pull_request]

defaults:
  run:
    working-directory: ./backend

jobs:
  backend_linter:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi
        pip install openai
        pip install langchain
        pip install langchain_chroma
        pip install langchain_community
        pip install langchain_openai
        pip install langgraph
        pip install gpt4all
        pip install pypdf
        pip install tiktoken
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
