name: Frontend linter (ESLint)
on: [pull_request]

defaults:
  run:
    working-directory: ./frontend

jobs:
  frontend_linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.10.0
      - name: yarn install
        run: yarn install
      - name: Linter (ESLint)
        run: yarn run eslint ./src
