name: Frontend tests (Jest)
on: [pull_request]

jobs:
  frontend_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Cloning repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 20.10.0
        uses: actions/setup-node@v2
        with:
          node-version: 20.10.0
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: |
          yarn test -- --coverage
          yarn run test:badges
          yarn run test:badges --input "./cov" --output "./badges"

