name: Greetings

on: [pull_request_target]

jobs:
  greeting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hello @${{ github.actor }}, thank you for submitting a 🚀 PR! To allow your work to be integrated as seamlessly as possible, we advise you to:
            - [ ] Verify your PR is **up-to-date with origin/develop.
            - [ ] Verify all Continuous Integration (CI) **checks are passing**.
