name: Services topology diagram
on: [pull_request]

jobs:
  services_diagram:
    name: Services topology diagram
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Diagram auto-generator
      run: |
        docker run --rm --tty -v $PWD:/data dbeniamine/docker-compose-viz-mermaid -v -p -v -dLR -M -otopology.svg
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Add new diagram
